### ISSUE TITLE
IGCS-GITC crash with Ni No Kuni 2 

### ISSUE THREAD

**Issue by bnthomason** [ghostinthecamera/IGCS-GITC#16] opened 2021-05-20 16:27 UTC
Hello! When I attempt to inject dll and go in game, I see the interface window, but immediately after, the game crashes (while going in-game). I am using Ni No Kuni 2 latest version and the latest version of IGC-GITC for Ni No Kuni 2 (v1.0.0)

I ran the game and the tool both as administrator.

**Comment by ghostinthecamera** [comment] 2021-06-08 11:17
Hi there, try injecting once you are loaded in to the game world and in control of the character

**Comment by ghostinthecamera** [comment] 2021-06-08 13:53
also - try this without running as administrator

**Comment by bnthomason** [comment] 2021-06-14 02:01
I tried this too, I'll post a vid showing the problem

**Comment by bnthomason** [comment] 2021-06-17 13:45
Hello again. Please check if this runs on the newest version of .NetFrameworkss build. I think that may be the culprit. I can't test with the .net framework it was built in because my computer can't downgrade .net frameworks. The other issue may be that the game was patched. (game version 4.00)

**Comment by bnthomason** [comment] 2021-06-26 14:58
https://www.youtube.com/watch?v=G-6_oMf1lR8

Another video showing the problem

**Comment by ghostinthecamera** [comment] 2021-06-27 17:48
Hi, i downloaded the games and the tools from github and it works absolutely fine for me. No crashes, the camera, timestop and hud toogle work perfectly. I have tested on game version 4.00 (this is the version the tools were developed on)

In that video you posted, you're injecting the tools at the menu. I already asked you to inject when you have loaded into the game world.

This is likely not an issue with the tools.

**Comment by bnthomason** [comment] 2021-06-27 19:25
Hey. I will post another video showing the problem

**Comment by bnthomason** [comment] 2021-06-27 19:31
https://youtu.be/zy_4J2ORtOY

This proves that there is a problem, at least on my machine. I don't know if there's a fix for just 1 machine.

**Comment by ghostinthecamera** [comment] 2021-06-27 21:41
I can't see the video, it's set to private.

I'm sorry but if I can't reproduce the issue then there's nothing I can do. I downloaded the game just to test it for you and it worked fine - without any issues.

The problem is more likely to sit with your particular set up then it is within the tools. 

Closing this issue.

**Closed by ghostinthecamera** 2021-06-27 21:41 UTC

**Comment by bnthomason** [comment] 2021-06-28 00:18
What do you mean setup? I made the video no longer private, but I doubt it will help with the "Reproduce". I guess I will have to wait until someone else makes a camera tool then, that actually works with my pc.

**Comment by ghostinthecamera** [comment] 2021-06-28 10:09
It means that whatever else you might have running at the same time(and from that video, you have a lot of stuff running) could be causing an issue. Given that it has worked for myself, and for everyone else, this is likely a problem specific to your computer.

No, i did nothing "fancy", it is not a cracked version, it was developed on the steam version, version 4.00 of the game to be exact.

The only thing i can suggest is closing every single program you have running, including anything that uses an overlay such as MSI Afternburner, Rivatuner etc - any other games, software etc including bandicam. EVERYTHING non essential. Turn off steam overlay for this game.

Redownload the tools binary from the releases page, run only Ni No Kuni 2 and try injecting in gameplay. This way you have at least tried to isolate the issue and if it works then you know one of these other pieces of software is causing a problem.

I hope you get it working

**Comment by bnthomason** [comment] 2021-06-28 17:45
Ok, update. Bad news gets worse. I closed all my programs, including bandicam, webbrowsers, (I don't have any antiviruses) anything that hooks or is non-essential. Still no dice. I got so frustrated that I decided to clean slate my computer, then install only steam, the game, and run it from there. It still didn't work. I then decided to post on another few forums (Superuser) to find out of anyone else could help me isolate the problem, but super user came back and said an hour later "This topic is closed until clarification or more details are posted.". So it looks as if I'm on my own. I would love to create a camera for myself, but I don't even understand pointers, and I've tried to learn, but it's way over my brain. I just want to control the camera, for basically any game, but alas, not every game has a controllable camera, most of them have to be modded or hacked, and those that do sometimes are outdated or don't work with my computer. Some do although.

So, now i've isolated the problem from any problematic programs, what is the culprit? I doubt it's system incompatibility, but it might be that.

**Comment by bnthomason** [comment] 2021-06-28 18:07
Ok, I got it to work, but only in menu and cutscene form. It crashed right when taking control of the character.

I wonder if it's not picking up the character location or camera data?

**Comment by ghostinthecamera** [comment] 2021-06-28 19:19
Highly unlikely it's not getting the camera data. Unless you have a significantly different version of the game.

What key are you pressing to activate the camera?

**Comment by ghostinthecamera** [comment] 2021-06-28 20:27
There is one last thing to try - it's a complete long shot, but it might work. 

Inject this DLL: https://1drv.ms/u/s!AsRiF1eWiROU2HnN4PZkOudpZul3?e=GXAS1d

This is a debug version, see if it makes a difference. Remember, inject once loaded INTO the game. It WILL crash if you load at the menu.

**Comment by bnthomason** [comment] 2021-06-28 21:06
Hello, I will try that and let you know.

It's wierd, tho, I didn't press any keys. It just crashes when in overworld and dungeon mode.

**Comment by bnthomason** [comment] 2021-06-28 21:18
The debug doesn't work at all... It's almost like a blank file. When I load it, it says "Injection Succeeded", but nothing happens, not even crash. Anyway, thanks for trying.

**Comment by ghostinthecamera** [comment] 2021-06-28 21:27
Sometimes the injector fails to inject even though it says success - trying it again usually fixes it.

Other than that, sorry, I have no idea what could be causing this.

**Comment by ghostinthecamera** [comment] 2025-09-08 11:29
Have you tried reselecting the .dll in the injector - i can see its using a relative path (".\nnk2tools etc") but try selecting the dll specifically.
